# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffbeca4a459656e0b333dc74c86daa20575f066aee9b010838321ab820b160ea6c9fc1cc0e5987c0ed87fc737901c78939de92851abe05d70c1b0a2703ea79b7

test:
  secret_key_base: 90f16e4f44f24dbf7b1e4ec2712a27442f459072b59be2d702b998b5d7f7be75375a9ae846f0f377cae13b76677d097ef0e0e0cd460e29f01ec6f072a2fbee3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
